### PR TITLE
added a film input reader

### PR DESCRIPTION
**Pull request by KirstenH**
added capability to run algorithms on a .mp4 file, run by replacing camera.py in the command line with the .mp4 filename

### CODE REVIEW

**Comment by SamCB** [comment]
Hey, thanks for this, sorry it took me so long to get back about this. I'm not sure importing the videos using the `import_module()` method is the cleanest way around it. I was thinking about how we handle plugins that require separate file inputs. I was thinking something along the lines of

```
python main.py example_function.py video.py -a video_fileA -a video_fileB -a video_folder/* annotator_function.py -a annotations/*.json
```

Where each `-a/--arg` flag after one of the modules we import is an argument for the initialiser. Then they could get passed into main like this:

``` python
main(function=("example_function.py", []),
     img_input=("video.py", ["video_fileA", "video_fileB", "video_folder/..."]),
     annotations=("annotator_function.py", ["annotations/...json"])
```

So we could just end up calling

``` python
img_input = import_module(img_input[0]).initialise(*img_input[1])
# I.E.
img_input = import_module("video.py").initalise("video_fileA", "video_fileB", "video_folder/...")
```

Keeps the style of importing modules. Means if at some point we want multiple different classes for handling video input differently we can use it. Means it's easy if we want to use more than one video file. Lays foundations for more file imports in the future (e.g. select image and attribute files). Maintains separation of concerns - the `initialise()` function in `video.py` can handle importing video; `main.py` doesn't need to know anything about how files work.

I'm not exactly sure how this argument system works. I think I've seen something a bit like it before, so I can have a go at it after work. Thoughts? Does this make any sense at all?

**Comment by SamCB** [comment]
So I made some changes to how the whole thing passes arguments, they're explained a bit in the `README` and moreso from calling `python main.py -h`.

To run the video file we should be able to call:

```
python main.py example_implementations/random_function.py video.py -i some_video_file.mp4
```

However I haven't been able to run it. Obviously I'm missing some codecs or something. Any ideas there? Eitherway, if you see this and can get it to work, feel free to merge it in.

**Comment by KirstenH** [comment]
Hey Sam, the design of your implementation does look much better. I may be able to have a look at it over the coming days in between treatments depending on how I'm feeling, but I'll let you know if I manage anything!

**Comment by SamCB** [comment]
No stress. I'm going to have another go at getting the video drivers working... once I get my laptop working first. 😕

**Comment by SamCB** [comment]
Couldn't get my video drivers working, but used this as a base for `imageset.py`. As such, it's been merged.

**Pull request merged**
